language: python

# sudo false implies containerized builds
sudo: false

python:
  - 3.6

install:
  - pip install -r requirements.txt
# command to run tests
script:
  - pytest

deploy:
  provider: heroku
  api_key:
    secure: 7ca670b3-7dfc-4823-883b-dd2d53eda87e
  app: nlp-projects
  on:
    repo: Wanke15/NLP-projects
